export enum Skeleton_ActorAnimation {
    Death_A = "Death_A",
    Death_A_Pose = "Death_A_Pose",
    Death_B = "Death_B",
    Death_B_Pose = "Death_B_Pose",
    Hit_A = "Hit_A",
    Hit_B = "Hit_B",
    Idle_A = "Idle_A",
    Idle_B = "Idle_B",
    Interact = "Interact",
    Jump_Full_Long = "Jump_Full_Long",
    Jump_Full_Short = "Jump_Full_Short",
    Jump_Idle = "Jump_Idle",
    Jump_Land = "Jump_Land",
    Jump_Start = "Jump_Start",
    PickUp = "PickUp",
    Running_A = "Running_A",
    Running_B = "Running_B",
    Spawn_Air = "Spawn_Air",
    Spawn_Ground = "Spawn_Ground",
    TPose = "T-Pose",
    Throw = "Throw",
    Use_Item = "Use_Item",
    Walking_A = "Walking_A",
    Walking_B = "Walking_B",
    Walking_C = "Walking_C"
}