export enum ActorAnimation {
    Death_A = "Death_A",
    Death_A_Pose = "Death_A_Pose",
    Death_B = "Death_B",
    Death_B_Pose = "Death_B_Pose",
    Hit_A = "Hit_A",
    Hit_B = "Hit_B",
    Idle_A = "Idle_A",
    Idle_B = "Idle_B",
    Interact = "Interact",
    Jump_Full_Long = "Jump_Full_Long",
    Jump_Full_Short = "Jump_Full_Short",
    Jump_Idle = "Jump_Idle",
    Jump_Land = "Jump_Land",
    Jump_Start = "Jump_Start",
    PickUp = "PickUp",
    Running_A = "Running_A",
    Running_B = "Running_B",
    Spawn_Air = "Spawn_Air",
    Spawn_Ground = "Spawn_Ground",
    TPose = "T-Pose",
    Throw = "Throw",
    Use_Item = "Use_Item",
    Walking_A = "Walking_A",
    Walking_B = "Walking_B",
    Walking_C = "Walking_C",

    // Melee
    Melee_1H_Attack_Chop = "Melee_1H_Attack_Chop",
    Melee_1H_Attack_Jump_Chop = "Melee_1H_Attack_Jump_Chop",
    Melee_1H_Attack_Slice_Diagonal = "Melee_1H_Attack_Slice_Diagonal",
    Melee_1H_Attack_Slice_Horizontal = "Melee_1H_Attack_Slice_Horizontal",
    Melee_1H_Attack_Stab = "Melee_1H_Attack_Stab",
    Melee_2H_Attack_Chop = "Melee_2H_Attack_Chop",
    Melee_2H_Attack_Slice = "Melee_2H_Attack_Slice",
    Melee_2H_Attack_Spin = "Melee_2H_Attack_Spin",
    Melee_2H_Attack_Spinning = "Melee_2H_Attack_Spinning",
    Melee_2H_Attack_Stab = "Melee_2H_Attack_Stab",
    Melee_2H_Idle = "Melee_2H_Idle",
    Melee_Block = "Melee_Block",
    Melee_Block_Attack = "Melee_Block_Attack",
    Melee_Block_Hit = "Melee_Block_Hit",
    Melee_Blocking = "Melee_Blocking",
    Melee_Dualwield_Attack_Chop = "Melee_Dualwield_Attack_Chop",
    Melee_Dualwield_Attack_Slice = "Melee_Dualwield_Attack_Slice",
    Melee_Dualwield_Attack_Stab = "Melee_Dualwield_Attack_Stab",
    Melee_Unarmed_Attack_Kick = "Melee_Unarmed_Attack_Kick",
    Melee_Unarmed_Attack_Punch_A = "Melee_Unarmed_Attack_Punch_A",
    Melee_Unarmed_Idle = "Melee_Unarmed_Idle",

    // Ranged
    Ranged_Bow_Aiming_Idle = "Ranged_Bow_Aiming_Idle",
    Ranged_Bow_Draw = "Ranged_Bow_Draw",
    Ranged_Bow_Draw_Up = "Ranged_Bow_Draw_Up",
    Ranged_Bow_Idle = "Ranged_Bow_Idle",
    Ranged_Bow_Release = "Ranged_Bow_Release",
    Ranged_Bow_Release_Up = "Ranged_Bow_Release_Up",
    Ranged_Magic_Raise = "Ranged_Magic_Raise",
    Ranged_Magic_Shoot = "Ranged_Magic_Shoot",
    Ranged_Magic_Spellcasting = "Ranged_Magic_Spellcasting",
    Ranged_Magic_Spellcasting_Long = "Ranged_Magic_Spellcasting_Long",
    Ranged_Magic_Summon = "Ranged_Magic_Summon",

    // Skeletons
    Skeletons_Awaken_Standing = "Skeletons_Awaken_Standing",
    Skeletons_Death = "Skeletons_Death",
    Skeletons_Death_Pose = "Skeletons_Death_Pose",
    Skeletons_Death_Resurrect = "Skeletons_Death_Resurrect",
    Skeletons_Idle = "Skeletons_Idle",
    Skeletons_Inactive_Floor_Pose = "Skeletons_Inactive_Floor_Pose",
    Skeletons_Inactive_Standing_Pose = "Skeletons_Inactive_Standing_Pose",
    Skeletons_Spawn_Ground = "Skeletons_Spawn_Ground",
    Skeletons_Taunt = "Skeletons_Taunt",
    Skeletons_Taunt_Longer = "Skeletons_Taunt_Longer",
    Skeletons_Walking = "Skeletons_Walking"
}