export enum AdventurerProp {
    ArrowBowBundle = "/models/props/adventurers/arrow_bow_bundle.gltf",
    ArrowBow = "/models/props/adventurers/arrow_bow.gltf",
    ArrowCrossbowBundle = "/models/props/adventurers/arrow_crossbow_bundle.gltf",
    ArrowCrossbow = "/models/props/adventurers/arrow_crossbow.gltf",
    Axe1Handed = "/models/props/adventurers/axe_1handed.gltf",
    Axe2Handed = "/models/props/adventurers/axe_2handed.gltf",
    Bow = "/models/props/adventurers/bow.gltf",
    BowWithString = "/models/props/adventurers/bow_withString.gltf",
    Crossbow1Handed = "/models/props/adventurers/crossbow_1handed.gltf",
    Crossbow2Handed = "/models/props/adventurers/crossbow_2handed.gltf",
    Dagger = "/models/props/adventurers/dagger.gltf",
    MugEmpty = "/models/props/adventurers/mug_empty.gltf",
    MugFull = "/models/props/adventurers/mug_full.gltf",
    Quiver = "/models/props/adventurers/quiver.gltf",
    ShieldBadgeColor = "/models/props/adventurers/shield_badge_color.gltf",
    ShieldBadge = "/models/props/adventurers/shield_badge.gltf",
    ShieldRoundBarbarian = "/models/props/adventurers/shield_round_barbarian.gltf",
    ShieldRoundColor = "/models/props/adventurers/shield_round_color.gltf",
    ShieldRound = "/models/props/adventurers/shield_round.gltf",
    ShieldSpikesColor = "/models/props/adventurers/shield_spikes_color.gltf",
    ShieldSpikes = "/models/props/adventurers/shield_spikes.gltf",
    ShieldSquareColor = "/models/props/adventurers/shield_square_color.gltf",
    ShieldSquare = "/models/props/adventurers/shield_square.gltf",
    Smokebomb = "/models/props/adventurers/smokebomb.gltf",
    SpellbookClosed = "/models/props/adventurers/spellbook_closed.gltf",
    SpellbookOpen = "/models/props/adventurers/spellbook_open.gltf",
    Staff = "/models/props/adventurers/staff.gltf",
    Sword1Handed = "/models/props/adventurers/sword_1handed.gltf",
    Sword2HandedColor = "/models/props/adventurers/sword_2handed_color.gltf",
    Sword2Handed = "/models/props/adventurers/sword_2handed.gltf",
    Wand = "/models/props/adventurers/wand.gltf"
}

export enum SkeletonProp {
    ArrowBroken = "/models/props/skeletons/Skeleton_Arrow_Broken.gltf",
    ArrowBrokenHalf = "/models/props/skeletons/Skeleton_Arrow_Broken_Half.gltf",
    Arrow = "/models/props/skeletons/Skeleton_Arrow.gltf",
    ArrowHalf = "/models/props/skeletons/Skeleton_Arrow_Half.gltf",
    Axe = "/models/props/skeletons/Skeleton_Axe.gltf",
    Blade = "/models/props/skeletons/Skeleton_Blade.gltf",
    Crossbow = "/models/props/skeletons/Skeleton_Crossbow.gltf",
    Quiver = "/models/props/skeletons/Skeleton_Quiver.gltf",
    ShieldLargeA = "/models/props/skeletons/Skeleton_Shield_Large_A.gltf",
    ShieldLargeB = "/models/props/skeletons/Skeleton_Shield_Large_B.gltf",
    ShieldSmallA = "/models/props/skeletons/Skeleton_Shield_Small_A.gltf",
    ShieldSmallB = "/models/props/skeletons/Skeleton_Shield_Small_B.gltf",
    Staff = "/models/props/skeletons/Skeleton_Staff.gltf"
}
